[build]
builder = "dockerfile"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"
startCommand = "./start.sh"

[variables]
MODE = "http"
NODE_ENV = "production"