[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 300
restartPolicyType = "on_failure"

[[services]]
name = "playwright-mcp-server"

[services.healthcheck]
path = "/health"
timeout = 300
interval = 30

[[services.variables]]
MODE = "http"

[services.resources]
memory = 1024
cpu = 0.5