[build]
builder = "nixpacks"

[deploy]
healthcheckPath = "/health"
healthcheckTimeout = 120
restartPolicyType = "on_failure"
startCommand = "npm run start:debug"

[variables]
MODE = "http"
NODE_ENV = "production"